version: "2"
linters:
  default: none
  enable:
    - bidichk
    - contextcheck
    - durationcheck
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nonamedreturns
    - paralleltest
    - prealloc
    - revive
    - staticcheck
    - tparallel
    - unused
    - whitespace
    - wrapcheck
  settings:
    goconst:
      ignore-tests: true
  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
